from __future__ import annotations

from pathlib import Path

from .graph import render_dependency_graph
from .models import PrDescription, PrProposal

__all__ = ["build_pr_description", "create_pr_proposal"]

_FIXED_RISK_NOTE = "PR is a proposal only; no auto-merge. Human approval required."


def _scan_to_lines(value):
    if isinstance(value, dict):
        return [f"{name}@{version}" for name, version in sorted(value.items())]
    if isinstance(value, list):
        names = sorted(
            {
                item.get("package", "")
                for item in value
                if isinstance(item, dict) and item.get("package")
            }
        )
        return names
    return []


def _repo_dir_from_plan(plan):
    if plan.manifest_patch is not None and plan.manifest_patch.path:
        return str(Path(plan.manifest_patch.path).parent)
    if plan.lockfile_plan is not None and getattr(plan.lockfile_plan, "cwd", None):
        return str(plan.lockfile_plan.cwd)
    return None


def _before_after_text(plan):
    verification = plan.verification
    if verification is not None:
        return _scan_to_lines(verification.scan_before), _scan_to_lines(
            verification.scan_after
        )
    repo_dir = _repo_dir_from_plan(plan)
    if repo_dir is None:
        return ["(no scan data available)"], ["(no scan data available)"]
    rendered = render_dependency_graph(repo_dir)
    return ["(before state unavailable)"], rendered.splitlines() or ["(no dependencies)"]


def _test_commands(ecosystem: str) -> list:
    if ecosystem == "go":
        commands = ["go test ./..."]
    elif ecosystem == "python":
        commands = ["python -m pytest"]
    else:
        commands = ["npm test"]
    commands.append("python -m pytest tests -q")
    return commands


def _scan_result(plan) -> dict:
    verification = plan.verification
    if verification is None:
        return {
            "resolved": False,
            "remaining": 0,
            "finding_type": None,
            "package": None,
        }
    return {
        "resolved": bool(verification.resolved),
        "remaining": len(verification.remaining),
        "finding_type": verification.finding_type,
        "package": verification.package,
    }


def build_pr_description(plan) -> PrDescription:
    finding = plan.finding
    finding_type = finding.get("finding_type", "")
    package = finding.get("package", "")
    ecosystem = finding.get("ecosystem", "npm")
    severity = finding.get("severity")
    file = finding.get("file")
    line = finding.get("line")

    title = f"chore(deps): remediate {finding_type} for {package}"

    summary_lines = [f"Finding type: {finding_type}", f"Package: {package}"]
    if severity is not None:
        summary_lines.append(f"Severity: {severity}")
    if file is not None:
        location = str(file)
        if line is not None:
            location = f"{location}:{line}"
        summary_lines.append(f"File/line: {location}")
    elif line is not None:
        summary_lines.append(f"Line: {line}")

    changed_files = []
    changes = []
    if plan.manifest_patch is not None:
        path = str(plan.manifest_patch.path)
        changed_files.append(path)
        changes.append(
            f"- `{path}`: add `{package}` to {plan.manifest_patch.kind or 'dependencies'}"
        )
    if plan.lockfile_plan is not None:
        applied = plan.lockfile_plan.applied
        if applied is not None:
            changed_files.append(str(applied.path))
            changes.append(f"- `{applied.path}`: updated lockfile to match manifest")
        else:
            changes.append("- lockfile: regenerated by package manager")
    if plan.verification is not None:
        changes.append(
            f"- Verified after remediation scan: resolved={plan.verification.resolved}"
        )

    before_lines, after_lines = _before_after_text(plan)

    test_commands = _test_commands(ecosystem)

    scan_result = _scan_result(plan)

    unresolved_risks = []
    if plan.verification is not None and plan.verification.remaining:
        for item in plan.verification.remaining:
            unresolved_risks.append(
                f"- {item.get('finding_type')} for {item.get('package')}"
            )
    if not unresolved_risks:
        unresolved_risks.append("- None identified.")
    unresolved_risks.append(f"- {_FIXED_RISK_NOTE}")

    body_lines = [
        "## Summary",
        "",
    ]
    body_lines.extend(f"- {item}" for item in summary_lines)
    body_lines.extend(
        [
            "",
            "## Changed files",
            "",
        ]
    )
    body_lines.extend(changes)
    body_lines.extend(
        [
            "",
            "## Before/After",
            "",
            "Before:",
        ]
    )
    body_lines.extend(f"- {item}" for item in before_lines)
    body_lines.extend(
        [
            "",
            "After:",
        ]
    )
    body_lines.extend(f"- {item}" for item in after_lines)
    body_lines.extend(
        [
            "",
            "## Test commands",
            "",
        ]
    )
    body_lines.extend(f"- `{command}`" for command in test_commands)
    body_lines.extend(
        [
            "",
            "## Scan result",
            "",
            f"resolved: {scan_result['resolved']}; "
            f"remaining findings: {scan_result['remaining']}",
            "",
            "## Unresolved risks",
            "",
        ]
    )
    body_lines.extend(unresolved_risks)

    return PrDescription(
        title=title,
        body="\n".join(body_lines),
        changed_files=changed_files,
        test_commands=test_commands,
        scan_result=scan_result,
        unresolved_risks=unresolved_risks,
    )


def _sanitize(value: str) -> str:
    return "".join(
        character if character.isalnum() else "-" for character in value
    ).strip("-")


def _default_branch_name(finding_type, package) -> str:
    type_segment = _sanitize(str(finding_type).lower())
    package_segment = _sanitize(str(package))
    return f"remediation/{type_segment}/{package_segment}"


def create_pr_proposal(
    repo_dir: str, plan, *, branch_name: str | None = None
) -> PrProposal:
    finding = plan.finding
    finding_type = finding.get("finding_type", "")
    package = finding.get("package", "")
    if branch_name is None:
        branch_name = _default_branch_name(finding_type, package)
    commit_message = f"{branch_name}: add {package} to manifest"
    if plan.pr_description is not None:
        description = plan.pr_description
    else:
        description = build_pr_description(plan)
    return PrProposal(
        branch_name=branch_name,
        commit_message=commit_message,
        description=description,
    )
